# Generated by Django 4.0.6 on 2022-09-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pantalones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=150)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Zapatilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=150)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='producto',
            new_name='camisetas',
        ),
    ]
